version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: casa_gastos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: casaGastos
      MYSQL_USER: casauser
      MYSQL_PASSWORD: casa123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - casa-network

  webapp:
    build: .
    container_name: casa_gastos_app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: casaGastos
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - casa-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:

networks:
  casa-network:
    driver: bridge