# Netlify deployment configuration
[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm start"
  port = 3002

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200