# Render.com deployment configuration
services:
  - type: web
    name: casa-gastos
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_MODEL
        value: gpt-4o-mini
    plan: free